- id: '1608029879336'
  alias: Kontor Kontakt
  description: Tænd lyset på kontor
  trigger:
  - device_id: 6ac4a37bab02c17d8d59126978dcb0c7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.kontor
  mode: single
- id: '1603285560454'
  alias: Vandskade Alarm
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 747b94d7e04d789e791ab2b31b40aa49
    entity_id: binary_sensor.opvaskemaskine
    domain: binary_sensor
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: Vandalarm Køkken
      message: Der er fundet vand under opvaskemaskine
      notification_id: water_alarm
  - service: notify.mobile_app_michael_phone
    data:
      title: Vandalarm Køkken
      message: Der er fundet vand under opvaskemaskine
      data:
        sticky: true
        persistent: true
        tag: water_alarm
        color: '#FF0000'
        channel: alert
        importance: high
  mode: single
- id: '1603734250810'
  alias: Støvsuger
  description: Start støvsuger dagligt
  trigger:
  - platform: time
    at: '10:00:00'
  - platform: zone
    entity_id: person.michael
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: person.camilla
    zone: zone.home
    event: leave
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.michael
      zone: zone.home
    - condition: zone
      entity_id: person.camilla
      zone: zone.home
    - condition: numeric_state
      entity_id: sensor.tumle_runtime_today
      above: '0'
  action:
  - device_id: 4c0a226ada01406eae600561e2ba4071
    domain: vacuum
    entity_id: vacuum.tumle
    type: clean
  mode: single
- id: '1603734502223'
  alias: Camilla har forladt UiU
  trigger:
  - entity_id: person.camilla
    event: leave
    platform: zone
    zone: zone.uiu
  - event_data:
      action: update_camilla_work_notification
    event_type: ''
    platform: event
  condition:
  - after: '11:00:00'
    before: '23:59:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - data:
      data:
        tag: camilla_home
      message: Forventet hjemme om {{ states('sensor.camilla_travel') }} min ({{ (now().strftime('%s')
        | int + (states('sensor.camilla_travel') | int * 60)) | timestamp_custom('%H:%M',
        false) }})
      title: Camilla har forladt kontoret
    service: notify.mobile_app_michaels_telefon
  mode: single
- id: '1603735485232'
  alias: Bryggersdør
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: bb55e91e30b0f5febbdf5ae5c2fd8244
    entity_id: binary_sensor.bryggersdoer
    domain: binary_sensor
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: doorbell_notification_revert
      snapshot_entities: light.kontor
  - service: light.turn_on
    data:
      entity_id: light.kontor
      rgb_color:
      - 255
      - 50
      - 50
      flash: long
  - delay: 00:00:03
  - service: scene.turn_on
    data:
      entity_id: scene.doorbell_notification_revert
  mode: single
- id: '1608305169136'
  alias: CO2 Notifikation
  description: Styrer CO2 notifikation
  trigger:
  - platform: numeric_state
    entity_id: sensor.netatmo_baunedalen_co2,sensor.netatmo_baunedalen_alrum_co2,sensor.netatmo_baunedalen_sovevaerelse_co2,sensor.netatmo_baunedalen_kontor_co2
    above: '1100'
  - platform: numeric_state
    entity_id: sensor.netatmo_baunedalen_co2,sensor.netatmo_baunedalen_alrum_co2,sensor.netatmo_baunedalen_sovevaerelse_co2,sensor.netatmo_baunedalen_kontor_co2
    below: '1100'
  - platform: time_pattern
    minutes: /15
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id:
        - sensor.netatmo_baunedalen_co2
        - sensor.netatmo_baunedalen_alrum_co2
        - sensor.netatmo_baunedalen_sovevaerelse_co2
        - sensor.netatmo_baunedalen_kontor_co2
        above: '1100'
      sequence:
      - service: script.notification_michael_hvis_hjemme
        data:
          title: Frisk Luft Alarm
          message: '"Alrum: {{ states(''sensor.netatmo_baunedalen_alrum_co2'') }}

            Stue: {{ states(''sensor.netatmo_baunedalen_co2'') }}

            Soveværelse: {{ states(''sensor.netatmo_baunedalen_sovevaerelse_co2'')
            }}

            Kontor: {{ states(''sensor.netatmo_baunedalen_kontor_co2'') }}"

            '
          tag: co2notification
    default:
    - service: script.notification_michael_hvis_hjemme
      data:
        message: clear_notification
        tag: co2notification
  mode: queued
  max: 10
- id: '1608315737292'
  alias: Vækkeur
  description: ''
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      max_brightness: 100
      light_entity: light.alrum_gra
      manual_time: 00:00:00
      timestamp_sensor: sensor.samsungs20_naeste_alarm
      sunrise_duration: 20
- id: '1608321006068'
  alias: Vaskemaskine
  description: ''
  use_blueprint:
    path: Sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      power_sensor: sensor.vaskemaskine_effekt
      starting_threshold: '5'
      starting_hysteresis: '5'
      finishing_threshold: '5'
      finishing_hysteresis: '5'
      actions:
      - service: script.notification_michael_hvis_hjemme
        data:
          title: Vaskemaskine
          message: Færdig
          tag: vaskemaskine
- id: '1608652073704'
  alias: Alrum Kontakt
  description: ''
  use_blueprint:
    path: poolcactus/zha-ikea-tradfri-on-off-switch-incl-dimmer.yaml
    input:
      remote: 4475ce491c875f9b94f70db48da09e67
      light:
        area_id: 5fef45b5bd4d42b8bda250c7e7e3d328
