  # Turn on lights when media player is idle
  - id: living_room_bright_light
    alias: "Living Room: Bright Light when Idle"
    trigger:
      - platform: state
        entity_id: media_player.living_room_media
        from: 'playing'
        to: 'paused'
      - platform: state
        entity_id: media_player.living_room_media
        from: 'playing'
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: template
          value_template: '{{ states.remote.living_room_harmony.state != "Music" }}'
    action:
      service: script.living_room_bright_light

  # Dim lights when media player starts playing
  - id: living_room_movie_light
    alias: "Living Room: Movie Lighting when Playing"
    trigger:
      - platform: state
        entity_id: media_player.living_room_media
        from: 'off'
        to: 'playing'
      - platform: state
        entity_id: media_player.living_room_media
        from: 'paused'
        to: 'playing'
    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.living_room_media
              state: 'movie'
            - condition: state
              entity_id: sensor.living_room_media
              state: 'tvshow'
    action:
      service: script.living_room_movie_light

  # Switch to Harmony activity Kodi when Kodi changes from idle
  - id: switch_to_kodi
    alias: "Living Room: Switch to Kodi"
    trigger:
      platform: state
      entity_id: media_player.living_room_kodi
      from: 'idle'
    condition:
      condition: template
      value_template: '{{ states.remote.living_room_harmony.state != "Kodi" }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.living_room_harmony
        activity: 'Kodi'

  # Switch to Harmony activity Chromecast when Chromecast switches from off or idle
  - id: switch_to_chromecast
    alias: "Living Room: Switch to Chromecast"
    trigger:
      - platform: state
        entity_id: media_player.living_room_cast
        from: 'off'
      - platform: state
        entity_id: media_player.living_room_cast
        from: 'idle'
    condition:
      condition: template
      value_template: '{{ states.remote.living_room_harmony.state != "Chromecast" }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.living_room_harmony
        activity: 'Chromecast'

  # Switch to Harmony activity Chromecast when Chromecast switches from off or idle
  - id: switch_to_music
    alias: "Living Room: Switch to Music"
    trigger:
      - platform: state
        entity_id: media_player.living_room_speaker
        from: 'off'
      - platform: state
        entity_id: media_player.living_room_speaker
        from: 'idle'
      - platform: state
        entity_id: media_player.all_speakers
        from: 'off'
      - platform: state
        entity_id: media_player.all_speakers
        from: 'idle'
    condition:
      condition: template
      value_template: '{{ states.remote.living_room_harmony.state != "Music" }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.living_room_harmony
        activity: 'Music'

  # Switch Harmony to off when chromecast turns off
  - id: poweroff_when_idle
    alias: "Living Room: PowerOff when Idle"
    trigger:
      platform: state
      entity_id: media_player.living_room_media
      to: 'off'
      for:
        minutes: 5
    condition:
      condition: template
      value_template: '{{ states.remote.living_room_harmony.state != "Off" }}'
    action:
      service: remote.turn_off
      data:
        entity_id: remote.living_room_harmony
