  # Turn on lights when media player is idle
  - id: living_room_bright_light
    alias: "Living Room: Bright Light when Idle"
    trigger:
      platform: state
      entity_id: media_player.living_room_media
      from: 'playing'
    condition:
      condition: sun
      after: sunset
    action:
      service: hue.hue_activate_scene
      data:
        group_name: Living Room
        scene_name: Bright

  # Dim lights when media player starts playing
  - id: living_room_movie_light
    alias: "Living Room: Movie Lighting when Playing"
    trigger:
      platform: state
      entity_id: media_player.living_room_media
      to: 'playing'
    condition:
      condition: sun
      after: sunset
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: Living Room
          scene_name: Movie
      - service: light.turn_off
        data:
          entity_id: light.hallway

  # Switch to Harmony activity Kodi when Kodi changes from idle
  - id: living_room_switch_to_kodi
    alias: "Living Room: Switch to Kodi"
    trigger:
      platform: state
      entity_id: media_player.living_room_kodi
      to: 'playing'
      for:
        seconds: 1
    condition:
      condition: template
      value_template: '{{ not is_state_attr("remote.living_room","current_activity","Kodi") }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: 'Kodi'

  # Switch to Harmony activity Chromecast when Chromecast switches from off or idle
  - id: living_room_switch_to_chromecast
    alias: "Living Room: Switch to Chromecast"
    trigger:
      platform: state
      entity_id: media_player.living_room_cast
      to: 'playing'
    condition:
      condition: template
      value_template: '{{ not is_state_attr("remote.living_room","current_activity","Chromecast") }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: 'Chromecast'

  # Switch to Harmony activity Chromecast when Chromecast switches from off or idle
  - id: living_room_switch_to_music
    alias: "Living Room: Switch to Music"
    trigger:
      platform: state
      entity_id:
        - media_player.living_room_speaker
        - media_player.all_speakers
      to: 'playing'
    condition:
      condition: template
      value_template: '{{ not is_state_attr("remote.living_room","current_activity","Music") }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.living_room
        activity: 'Music'

  # Switch Harmony to off when chromecast turns off
  - id: living_room_poweroff_when_idle
    alias: "Living Room: PowerOff when Idle"
    trigger:
      platform: state
      entity_id: media_player.living_room_media
      to: 'off'
      for:
        minutes: 5
    condition:
      condition: template
      value_template: '{{ not is_state("remote.living_room","off") }}'
    action:
      service: remote.turn_off
      data:
        entity_id: remote.living_room

  # Switch to Harmony activity Kodi when Kodi changes from idle
  - id: bedroom_switch_to_kodi
    alias: "Bedroom: Switch to Kodi"
    trigger:
      platform: state
      entity_id: media_player.bedroom_kodi
      to: 'playing'
      for:
        seconds: 1
    condition:
      condition: template
      value_template: '{{ not is_state_attr("remote.bedroom","current_activity","Kodi") }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.bedroom
        activity: 'Kodi'

  # Switch to Harmony activity Chromecast when Chromecast switches from off or idle
  - id: bedroom_switch_to_chromecast
    alias: "Bedroom: Switch to Chromecast"
    trigger:
      platform: state
      entity_id: media_player.bedroom_cast
      to: 'playing'
    condition:
      condition: template
      value_template: '{{ not is_state_attr("remote.bedroom","current_activity","Chromecast") }}'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.bedroom
        activity: 'Chromecast'

  # Switch Harmony to off when chromecast turns off
  - id: bedroom_poweroff_when_idle
    alias: "Bedroom: PowerOff when Idle"
    trigger:
      platform: state
      entity_id: media_player.bedroom_media
      to: 'off'
      for:
        minutes: 5
    condition:
      condition: template
      value_template: '{{ not is_state("remote.bedroom","off") }}'
    action:
      service: remote.turn_off
      data:
        entity_id: remote.bedroom

  # Notify when lights are on but noone is home
  - id: lights_on_empty_home
    alias: "Lights on with noone home"
    trigger:
      - platform: state
        entity_id:
          - device_tracker.mbw_oneplus_6
          - device_tracker.milla_oneplus_5t
        to: 'not_home'
        for:
          minutes: 5
      - platform: state
        entity_id: group.all_lights
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.mbw_oneplus_6
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.milla_oneplus_5t
          state: 'not_home'
        - condition: state
          entity_id: group.all_lights
          state: 'on'
    action:
      service: notify.html5notify
      data:
        title: "Lights are on"
        message: "There are lights on, but noone is home."
        target: 'mbw_oneplus_6'
        data:
          tag: 'turn_off_lights'
          actions:
            - title: "Turn off lights"
              action: 'turn_off_lights'
  # Turn of lights when notification is pressed
  - id: lights_on_empty_home_clicked
    alias: "Lights on notification clicked"
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        tag: 'turn_off_lights'
    action:
      service: light.turn_off

  # Alarm clock automation
  - id: alarm_clock
    alias: "Alarm Clock"
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == states('sensor.alarm_clock_time') }}"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_clock_active
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.alarm_clock_weekend
              state: 'on'
            - condition: time
              weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
    action:
      - service: light.turn_on
        entity_id: light.bedroom
      - service: media_player.play_media
        entity_id: media_player.bedroom_kodi
        data:
          media_content_type: "CHANNEL"
          media_content_id: 2
