  # Send notification when there is an update available
  - alias: Update Notifications
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.html5notify_galaxys7
      data:
        title: 'New Home Assistant Release'
        message: 'Home Assistant {{ states.updater.updater.state }} is now available'

  # Turn on lights when media player is idle
  - alias: "Stue: Bright Light when Idle"
    trigger:
      - platform: state
        entity_id: media_player.media_stue
        from: 'playing'
        to: 'paused'
      - platform: state
        entity_id: media_player.media_stue
        from: 'playing'
        to: 'off'
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      service: script.stue_bright_mode

  # Dim lights when media player starts playing
  - alias: "Stue: Movie Lighting when Playing"
    trigger:
      - platform: state
        entity_id: media_player.media_stue
        from: 'off'
        to: 'playing'
      - platform: state
        entity_id: media_player.media_stue
        from: 'paused'
        to: 'playing'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.media_stue
              state: 'movie'
            - condition: state
              entity_id: sensor.media_stue
              state: 'tvshow'
    action:
      service: script.stue_movie_mode

  # Switch to Harmony activity Kodi when Kodi Stue switches from off to idle
  - alias: "Stue: Switch to Kodi"
    trigger:
      platform: state
      entity_id: media_player.kodi_stue
      from: 'idle'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.harmonystue
        activity: 'Kodi'

  # Switch to Harmony activity Chromecast when Chromecast switches from off to idle
  - alias: "Stue: Switch to Chromecast"
    trigger:
      platform: state
      entity_id: media_player.chromestue
      from: 'off'
    action:
      service: remote.turn_on
      data:
        entity_id: remote.harmonystue
        activity: 'Chromecast'

  # Switch Harmony to off when chromecast turns off
  - alias: "Stue: PowerOff when Idle"
    trigger:
      platform: state
      entity_id: media_player.media_stue
      to: 'off'
      for:
        minutes: 5
    action:
      service: remote.turn_off
      data:
        entity_id: remote.harmonystue
