- platform: template
  sensors:
    anyone_home:
      device_class: occupancy
      friendly_name: 'Nogen hjemme'
      value_template: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"