homeassistant:
  name: Home
  latitude: !secret home_lattitude
  longitude: !secret home_longtitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html

config:

http:
  api_password: !secret api_password
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warning
  logs:
    DenonAVR: critical

recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.date
      - sensor.time

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.yr_symbol

# Track the sun
sun:

map:

notify:
  platform: html5
  name: html5-notify
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id
#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  username: !secret mqtt_username
#  password: !secret mqtt_password
ifttt:
  key: !secret ifttt_key
tado:
  username: !secret tado_username
  password: !secret tado_password
google_assistant: !include google_assistant.yaml
hue: !include hue.yaml

zone: !include zones.yaml
device_tracker: !include device_trackers.yaml
media_player: !include media_players.yaml
sensor: !include sensors.yaml
remote: !include remotes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
#switch: !include switches.yaml
#input_select: !include input_selects.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
