homeassistant:
  name: Home
  customize: !include customize.yaml
  latitude: !secret home_lattitude
  longitude: !secret home_longtitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  auth_providers:
   - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

config:

http:
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://cast.home-assistant.io
  trusted_proxies: 172.18.0.0/16
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

updater:
discovery:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warning

recorder:
  db_url: !secret db_url
  purge_interval: 7
  purge_keep_days: 14
  exclude:
    entities:
      - sensor.date
      - sensor.time

history:

logbook:
  exclude:
    entities:
      - sensor.yr_symbol

system_health:

sun:

person:

mobile_app:

wake_on_lan:

notify:
  - platform: html5
    name: html5-notify
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: webostv
    host: 10.0.1.70
    name: living_room_tv

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: false

ifttt:
  key: !secret ifttt_key

speedtestdotnet:

nzbget:
  host: !secret nzbget_host
  port: !secret nzbget_port
  ssl: false
  username: !secret nzbget_username
  password: !secret nzbget_password
        
transmission:
  host: !secret transmission_host
  port: !secret transmission_port
  username: !secret transmission_username
  password: !secret transmission_password

vacuum:
  - platform: roomba
    host: !secret roomba_host
    username: !secret roomba_username
    password: !secret roomba_password
    name: !secret roomba_name

bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: "rest_of_world"

automation: !include automations.yaml
zone: !include zones.yaml
remote: !include remotes.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
cast: !include cast.yaml
