homeassistant:
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

config:

http:
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://cast.home-assistant.io
  trusted_proxies: 172.18.0.0/16
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

updater:
discovery:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warning

recorder:
  db_url: !secret db_url
  purge_keep_days: 14
  exclude:
    entities:
      - sensor.date
      - sensor.time

history:

logbook:
  exclude:
    entities:
      - sensor.yr_symbol

system_health:

sun:

person:

mobile_app:

wake_on_lan:

browser_mod:
  prefix: "client_"
  devices:
    99980b13-dabc9563:
      name: client_michael_work_laptop
      disable:
      - light
      - media_player
    a53691e0_6b9d4dc8:
      name: client_oneplus6
      disable:
      - light
      - media_player
  disable:
    - light
    - media_player

notify:

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

ifttt:
  key: !secret ifttt_key

speedtestdotnet:

docker_monitor:
  monitored_conditions:

nzbget:
  host: nzbget
  port: !secret nzbget_port
  ssl: false
  username: !secret nzbget_username
  password: !secret nzbget_password

bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: "rest_of_world"

webostv:
  host: 10.0.1.70
  name: 'Living Room TV'
  customize:
    sources:
      - 'Home Theatre'
      - 'PS3'
      - 'YouTube'
      - 'TV 2 PLAY'
      - 'Netflix'
      - 'Plex'
      - 'UHD Fireplace'

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

automation: !include automations.yaml
remote: !include remotes.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
binary_sensor: !include binary_sensor.yaml
script: !include scripts.yaml
