homeassistant:
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

config:

cloud:

http:
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://cast.home-assistant.io
  trusted_proxies: 10.0.10.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

updater:
discovery:
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warning

recorder:
  db_url: !secret db_url
  purge_keep_days: 14
  exclude:
    entities:
      - sensor.date
      - sensor.time

history:

logbook:
  exclude:
    entities:
      - sensor.yr_symbol

system_health:

sun:

person:

mobile_app:

wake_on_lan:

notify:
  - platform: html5
    name: HTML5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: group
    name: both_phones
    services:
      - service: mobile_app_michaels_telefon
      - service: mobile_app_camilla_phone

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
spotcast:
  sp_dc: !secret spotify_dc
  sp_key: !secret spotify_key

ifttt:
  key: !secret ifttt_key

speedtestdotnet:

nzbget:
  host: nzbget
  port: !secret nzbget_port
  ssl: false
  username: !secret nzbget_username
  password: !secret nzbget_password

bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: "rest_of_world"

webostv:
  host: 10.0.1.72
  name: 'Alrum TV'
  customize:
    sources:
      - 'Home Theatre'
      - 'PS3'
      - 'YouTube'
      - 'TV 2 PLAY'
      - 'Netflix'
      - 'Plex'
      - 'UHD Fireplace'

automation: !include automations.yaml
sensor: !include sensors.yaml
media_player: !include media_players.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
binary_sensor: !include binary_sensor.yaml
script: !include scripts.yaml
