homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 10.0.0.0/16
        - 2a05:f6c7:2186::/48
      trusted_users:
        10.0.0.0/16: 53299a6d0c9d4343b50085530bb25314
        2a05:f6c7:2186::/48: 53299a6d0c9d4343b50085530bb25314
      allow_bypass_login: true
  allowlist_external_dirs:
    - /config

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources: !include resources.yaml
  dashboards:
    lovelace-tablet:
      mode: yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: false
      require_admin: false
      filename: dashboards/tablet.yaml
    lovelace-alarm:
      mode: yaml
      title: Alarm
      icon: mdi:shield-home
      show_in_sidebar: false
      require_admin: false
      filename: dashboards/alarm.yaml

config:

my:

cloud:

http:
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://cast.home-assistant.io
  trusted_proxies:
    - 10.0.60.10/32
  use_x_forwarded_for: true
  ip_ban_enabled: false
  login_attempts_threshold: 3

updater:

zeroconf:

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: warning
  logs:
    gardena.smart_system: warning

system_health:

#media_source:

recorder:
  db_url: !secret db_url
  purge_keep_days: 14
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time

history:

logbook:
  exclude:
    entities:
      - sensor.yr_symbol
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time

influxdb:
  api_version: 2
  ssl: false
  host: influxdb
  port: 8086
  token: !secret influxdb_token
  organization: mbw.dk
  bucket: homeassistant
  tags:
    source: homeassistant
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entity_globs: "*"

rest_command:
  pipup:
    url: http://10.0.10.20:7979/notify
    content_type: "application/json"
    verify_ssl: false
    method: "post"
    timeout: 20
    payload: >
      {
        "duration": "{{ duration }}",
        "position": "{{ position }}",
        "title": "{{ title }}",
        "titleColor": "{{ titleColor }}",
        "titleSize": "{{ titleSize }}",
        "message": "{{ message }}",
        "messageColor": "{{ messageColor }}",
        "messageSize": "{{ messageSize }}",
        "backgroundColor": "{{ backgroundColor }}",
        "media": { 
          "{{ mediaType }}": {
            "uri": "{{ uri }}", 
            "width": "{{ width }}"
          }
        }
      }

stream:

camera:
  - platform: generic
    name: Hoveddør
    still_image_url: http://homeassistant.local:8123{{ states.camera.hoveddor_snapshot.attributes.entity_picture }}
    stream_source: rtsp://ring-mqtt:8554/54e01919cdf6_live
  - platform: xiaomi_cloud_map_extractor
    name: roborock_s7_map
    host: 10.0.20.91
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: de
    scan_interval:
      seconds: 30
    auto_update: false
    draw: ["all"]
    map_transformation:
      scale: 1.5
      rotate: 0
      trim:
        top: 20
        bottom: 20
        left: 10
        right: 10
    attributes:
      - calibration_points
      - rooms
      - zones
      - vacuum_room

sun:

person:

mobile_app:

wake_on_lan:

energy:

#modbus:
#  - name: smart-me
#    type: tcp
#    host: 10.0.20.144
#    port: 502
#    sensors:
#      - name: Smart-Me Counter
#        slave: 1
#        address: 8267
#        input_type: holding
#        count: 2
#        scale: 0.001
#        precision: 2
#        scan_interval: 30
#        device_class: energy
#        unit_of_measurement: kWh
#        state_class: total_increasing

home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

nordpool:

utility_meter:
  gasforbrug_manedlig:
    name: Gasforbrug Månedlig
    source: input_number.gasforbrug
    cycle: monthly
  vandforbrug_manedlig:
    name: Vandforbrug Månedlig
    source: input_number.vandforbrug
    cycle: monthly

emulated_roku:
  servers:
    - name: Home Assistant
      listen_port: 8060

emulated_hue:
  listen_port: 80
  host_ip: 10.0.20.20
  advertise_ip: 10.0.20.20
  expose_by_default: false
  entities:
    light.alrum:
      hidden: false
    light.kokken:
      hidden: false
    light.udestue:
      hidden: false
    light.alrum_spisebord:
      hidden: false

notify:
  - platform: html5
    name: HTML5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - platform: group
    name: both_phones
    services:
      - service: mobile_app_michaels_telefon
      - service: mobile_app_camillas_telefon

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotify_dc
  sp_key: !secret spotify_key

ifttt:
  key: !secret ifttt_key

webostv:
  host: 10.0.10.25
  name: "Alrum TV"
  customize:
    sources:
      - "Home Theatre"
      - "PS3"
      - "YouTube"
      - "TV 2 PLAY"
      - "Netflix"
      - "Plex"
      - "UHD Fireplace"

browser_mod:
  prefix: "browser_"
  devices:
    bd62425d-cb008492:
      name: Alarm Dashboard
      force_stay_awake: true
      disable:
        - media_player
    763a9f90-6da3cfc1:
      name: Kontor Dashboard
      force_stay_awake: true
      disable:
        - media_player
    d02cd761-5c4c5bf1:
      name: Køkken Dashboard
      force_stay_awake: true
      disable:
        - media_player
  disable:
    - all

automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
media_player: !include media_players.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
