- platform: universal
  name: Alrum Media
  children:
    - media_player.alrum_kodi
    - media_player.shield
    - media_player.alrum_shield
    - media_player.alrum_tv
  commands:
    turn_on:
      service: remote.turn_on
      data_template:
        entity_id: remote.alrum_remote
        activity: Kodi
    turn_off:
      service: remote.turn_off
      data:
        entity_id: remote.alrum_remote
    volume_up:
      service: media_player.volume_up
      target:
        entity_id: media_player.alrum_tv
    volume_down:
      service: media_player.volume_down
      target:
        entity_id: media_player.alrum_tv
    volume_set:
      service: media_player.volume_set
      target:
        entity_id: media_player.alrum_tv
      data:
        volume_level: "{{ volume_level }}"
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id: media_player.alrum_tv
        is_volume_muted: '{{ not state_attr(''media_player.alrum_tv'', ''is_volume_muted'') }}'
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.alrum_shield
        source: '{{ source }}'
  attributes:
    is_volume_muted: media_player.alrum_tv|is_volume_muted
    volume_level: media_player.alrum_tv|volume_level
    source: media_player.alrum_shield|source
    source_list: media_player.alrum_shield|source_list
- name: Alrum Shield
  platform: androidtv
  host: 10.0.10.20
  exclude_unnamed_apps: true
  state_detection_rules:
      'com.google.android.tvlauncher':
      - 'standby'
      'com.netflix.ninja':
      - 'media_session_state'
      'dk.dr.tvplayer':
      - 'playing':
          'wake_lock_size': 6
      - 'playing':
          'wake_lock_size': 5
      - 'playing':
          'wake_lock_size': 4
      - 'playing':
          'wake_lock_size': 3
      - 'paused':
          'wake_lock_size': 2
      - 'paused':
          'wake_lock_size': 1
      - 'standby'
      'dk.tv2.tv2playtv':
      - 'playing':
          'wake_lock_size': 6
      - 'playing':
          'wake_lock_size': 5
      - 'playing':
          'wake_lock_size': 4
      - 'playing':
          'wake_lock_size': 3
      - 'paused':
          'wake_lock_size': 2
      - 'paused':
          'wake_lock_size': 1
      - 'standby'
  apps:
      com.google.android.tvlauncher: 'Launcher'
      com.viaplay.android: 'Viaplay'
      dk.tv2.tv2playtv: 'TV2 Play'
      dk.dr.tvplayer: 'DRTV'
      com.spotify.tv.android: ''
      tv.twitch.android.app: ''
      com.android.vending: ''
