- platform: template
  sensors:
    oneplus6_battery:
      friendly_name: 'Oneplus 6 Battery'
      value_template: "{{ state_attr('device_tracker.michael_phone', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery
    oneplus5t_battery:
      friendly_name: 'Oneplus 5t Battery'
      value_template: "{{ state_attr('device_tracker.camilla_phone', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery
    tumle_battery:
      friendly_name: 'Tumle Battery'
      value_template: "{{ state_attr('vacuum.tumle', 'battery_level') }}"
      icon_template: "{{ state_attr('vacuum.tumle', 'battery_icon') }}"
      unit_of_measurement: '%'
      device_class: battery
    living_room_co2:
      friendly_name: 'Living Room CO2'
      value_template: "{{ states('sensor.netatmo_savannehuset_living_room_co2') }}"
      icon_template: 'mdi:periodic-table-co2'
    bedroom_co2:
      friendly_name: 'Bedroom CO2'
      value_template: "{{ states('sensor.netatmo_savannehuset_bedroom_co2') }}"
      icon_template: 'mdi:periodic-table-co2'
    office_co2:
      friendly_name: 'Office CO2'
      value_template: "{{ states('sensor.netatmo_savannehuset_office_co2') }}"
      icon_template: 'mdi:periodic-table-co2'
    camilla_transport_destination:
      value_template: >-
        {% if (now().hour > 12 and not is_state('device_tracker.camilla_phone', 'home')) or is_state('device_tracker.camilla_phone', 'UiU') %}
          Home
        {% else %}
          UiU
        {% endif %}
    michael_transport_destination:
      value_template: >-
        {% if (now().hour > 12 and not is_state('device_tracker.michael_phone', 'home')) or is_state('device_tracker.michael_phone', 'Configit') %}
          Home
        {% else %}
          Configit
        {% endif %}
- platform: version
  source: local
- platform: version
  source: docker
- platform: netatmo
- platform: google_travel_time
  name: Michael Travel
  api_key: !secret google_apikey
  origin: device_tracker.michael_phone
  destination: sensor.michael_transport_destination
  scan_interval: 3600
  options:
    mode: transit
- platform: google_travel_time
  name: Camilla Travel
  api_key: !secret google_apikey
  origin: device_tracker.camilla_phone
  destination: sensor.camilla_transport_destination
  scan_interval: 3600
  options:
    mode: driving
