- platform: template
  sensors:
    tv_stats:
      entity_id:
        - sensor.living_room_tv_on_today
        - sensor.living_room_tv_on_yesterday
      friendly_name: TV Stats
      value_template:  >-
          {% if is_state('media_player.living_room_media', 'Off') %}
            Off
          {% else %}
            On
          {% endif %}
      icon_template: mdi:television
      attribute_templates:
        today: '{{ state_attr(''sensor.living_room_tv_on_today'', ''value'') }}'
        yesterday: '{{ state_attr(''sensor.living_room_tv_on_yesterday'', ''value'') }}'
- platform: uptime
- platform: version
  source: local
- platform: version
  source: docker
- platform: google_travel_time
  name: Michael Travel
  api_key: !secret google_apikey
  origin: device_tracker.michael_phone
  destination: Home
  scan_interval: 3600
  options:
    mode: driving
- platform: google_travel_time
  name: Camilla Travel
  api_key: !secret google_apikey
  origin: device_tracker.camilla_phone
  destination: Home
  scan_interval: 3600
  options:
    mode: transit
- platform: history_stats
  name: Living Room TV on Today
  entity_id: media_player.living_room_tv
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Living Room TV on Yesterday
  entity_id: media_player.living_room_tv
  state: 'on'
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    hours: 24
- platform: history_stats
  name: Tumle Runtime Today
  entity_id: vacuum.tumle
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: Michael Home
  entity_id: person.michael
  state: 'home'
  end: '{{ now() }}'
  type: ratio
  duration:
    days: 7
- platform: history_stats
  name: Camilla Home
  entity_id: person.camilla
  state: 'home'
  end: '{{ now() }}'
  type: ratio
  duration:
    days: 7
